### ISSUE TITLE
Using `urkel` optimized lib with smaller key sizes

### ISSUE THREAD

**Issue by nijynot** [handshake-org/urkel#11]
Wondering if it's possible to use keys of smaller size, i.e. keys that are less than 32 bytes.
You could pad the end of the keys before inserting them - is that a viable option?

For example, an urkel tree that takes 20 byte keys should not look any different from an urkel tree that takes 32 byte keys, given that you insert 20 byte keys padded with 12 bytes at the end? So I imagine there would not be significant performance gains to reducing the actual key length in the code?

**Comment by pinheadmz** [comment]
If I recall the construction correctly, there is no need to do this. The tree grows downwards as collisions are introduced into the tree. 

For example, starting with a totally empty tree, a 32-byte key is only one layer deep. If any they key is added with the same starting bit, that's when the second layer is added and now we are two layers deep with two keys. There is an illustration in the Handshake whitepaper.

**Comment by nijynot** [comment]
@pinheadmz Hmm, ok, if I've understood correctly, a simple zero padding to the end of the keys should suffice (as new layers are only added when collisions occur)?

**Comment by pinheadmz** [comment]
I'm not sure I understand. What are you trying to do? You could just initialize an Urkel tree with 160 bit depth and you won't need padding.

**Comment by nijynot** [comment]
Sorry, was browsing through the code now and just saw that. :man_facepalming:
Don't know how I missed that! Thanks for the help, closing
