### ISSUE TITLE
Root tree cache and proofs

### ISSUE THREAD

**Issue by nodech** [handshake-org/urkel#20]
Getting old tree Root Hashes are only necessary when we need to generate proofs. That request even though is rate limited should have consistent response times and not depend on the state of the tree.

  In the current released version, the first request of the incorrect root hash (or really old one) will prompt the tree to lookup all previous root hashes on the disk until the hash is found or we looked up everything. This request will take some time and will be noticeably slow. After first run, root cache will have all the root hashes in the tree and the lastMeta (used as indexing pointer in this case) will be set to the first one. (never change) This makes subsequent requests to the incorrect/old root hashes quick, we either have the hash in cache or not. lastMeta is already at the oldest and wont move further in the past, resulting in quick response time.

  Even though it's the one request, I believe caching should be done on open instead and have consistent response times for the proofs.

  Recent fix to lastMeta (#16), which makes `lastMeta` consistent with its name and updates it every time new root hash is committed, makes this issue more frequent (every 36 blocks we can get 1 slow lookup for incorrect root hash).

  Even though we could easily fix #16 by introducing separate meta for indexing/caching, I believe instead we should change how we approach the look ups in the first place.

  We can use `cache` as the main source of truth for the tree root hashes in the past and never go through disk twice and go to the disk when opening the tree. We can optionally add limitations (additional parameter, e.g. `initialRootHashCacheCount=100`) and only fixed number of hashes and ignore any root hash past that. (ofc initialRootHashCacheCount=-1 - index everything)

  This problem was discovered by @pinheadmz.

**Comment by pinheadmz** [comment]
I like the idea of caching the latest 100 or so roots, and keeping that number fixed so it doesn't get crazy as the chain grows into the future. 100 is probably even overkill but if its fast enough thats ok. We also need to address in hsd how we handle missing tree roots, and send polite `404`s to the requesting client.
